# Generated by Django 4.2.27 on 2026-04-13 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0008_roledefinition'),
        ('intake', '0004_intakeselectedcandidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('work_order_number', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('worker_full_name', models.CharField(blank=True, max_length=255)),
                ('worker_email', models.EmailField(blank=True, max_length=254)),
                ('worker_phone', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='draft', max_length=16)),
                ('approval_status', models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_started', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime_enabled', models.BooleanField(default=False)),
                ('overtime_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('work_location_label', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('approval_chain_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='approvals.approvalchain')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='masterdata.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_decided', to=settings.AUTH_USER_MODEL)),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='intake.intakerequest')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='masterdata.legalentity')),
                ('role_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='masterdata.roledefinition')),
                ('selected_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='intake.intakeselectedcandidate')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='masterdata.site')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_submitted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='masterdata.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant_id', 'status', 'created_at'], name='workorders__tenant__f16785_idx'), models.Index(fields=['tenant_id', 'approval_status', 'created_at'], name='workorders__tenant__4f7b8d_idx'), models.Index(fields=['intake', 'status'], name='workorders__intake__4f8539_idx'), models.Index(fields=['supplier', 'status'], name='workorders__supplie_038466_idx'), models.Index(fields=['created_by', 'created_at'], name='workorders__created_169a0d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(check=models.Q(('bill_rate__isnull', True), ('bill_rate__gte', 0), _connector='OR'), name='workorder_bill_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(check=models.Q(('pay_rate__isnull', True), ('pay_rate__gte', 0), _connector='OR'), name='workorder_pay_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(check=models.Q(('hours_per_week__isnull', True), ('hours_per_week__gte', 0), _connector='OR'), name='workorder_hours_per_week_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(check=models.Q(('overtime_multiplier__isnull', True), ('overtime_multiplier__gt', 0), _connector='OR'), name='workorder_overtime_multiplier_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(check=models.Q(('estimated_cost__isnull', True), ('estimated_cost__gte', 0), _connector='OR'), name='workorder_estimated_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(check=models.Q(('budget_amount__isnull', True), ('budget_amount__gte', 0), _connector='OR'), name='workorder_budget_amount_gte_0'),
        ),
    ]
