# Generated by Django 4.2.30 on 2026-07-29 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='supplier_acceptance_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Supplier Acceptance'), ('accepted', 'Accepted'), ('changes_requested', 'Changes Requested')], db_index=True, default='not_started', max_length=24),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supplier_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supplier_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_supplier_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supplier_change_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supplier_change_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_supplier_changes_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supplier_response_notes',
            field=models.TextField(blank=True),
        ),
    ]
