# Generated by Django 4.2.27 on 2026-02-26 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('engagement_type', models.CharField(choices=[('staffing', 'Staffing'), ('sow', 'SOW'), ('other', 'Other')], default='staffing', max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('worker_count', models.PositiveIntegerField(blank=True, null=True)),
                ('target_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_unit', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='hourly', max_length=16)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='masterdata.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='masterdata.site')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests_submitted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='masterdata.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('snapshot_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='intake.intakerequest')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('intake', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['status', 'created_at'], name='intake_inta_status_8adbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['created_by', 'created_at'], name='intake_inta_created_6681fa_idx'),
        ),
    ]
