# Generated by Django 4.2.27 on 2026-04-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakerequest',
            name='qualifications_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='IntakeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('qualification_type', models.CharField(choices=[('skill', 'Skill'), ('certification', 'Certification'), ('education', 'Education'), ('language', 'Language'), ('tool', 'Tool'), ('other', 'Other')], default='skill', max_length=32)),
                ('group', models.CharField(choices=[('must_have', 'Must Have'), ('nice_to_have', 'Nice To Have')], default='must_have', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('knockout', models.BooleanField(default=False)),
                ('response_mode', models.CharField(choices=[('years', 'Years of Experience'), ('rating', 'Rating'), ('yes_no', 'Yes / No'), ('text', 'Text')], default='years', max_length=16)),
                ('min_years', models.PositiveIntegerField(default=0)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=16)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='intake.intakerequest')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['intake', 'group'], name='intake_inta_intake__2694df_idx'), models.Index(fields=['qualification_type', 'response_mode'], name='intake_inta_qualifi_b76b6c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='intakequalification',
            constraint=models.UniqueConstraint(fields=('intake', 'sequence'), name='intake_qualification_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='intakequalification',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='intake_qualification_sequence_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='intakequalification',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 1), ('weight__lte', 5)), name='intake_qualification_weight_1_5'),
        ),
    ]
