# Generated by Django 4.2.27 on 2026-04-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('masterdata', '0008_roledefinition'),
        ('rates', '0001_initial'),
        ('intake', '0002_intakerequest_qualifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakerequest',
            name='approval_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='approvals.approvalchain'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='approval_chain_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='approval_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='approval_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_started', max_length=16),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='masterdata.legalentity'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='overtime_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='overtime_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='rate_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='rates.ratecard'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='role_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='masterdata.roledefinition'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='state_province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
