# Generated by Django 4.2.27 on 2026-04-13 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_roledefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0003_intakerequest_approval_chain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSelectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('available_start_date', models.DateField(blank=True, null=True)),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_candidates', to='intake.intakerequest')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_selected_candidates_submitted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_selected_candidates', to='masterdata.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['intake', 'status'], name='intake_inta_intake__1488cc_idx'), models.Index(fields=['supplier', 'status'], name='intake_inta_supplie_81993c_idx'), models.Index(fields=['submitted_by', 'created_at'], name='intake_inta_submitt_9151d6_idx')],
            },
        ),
    ]
