# Generated by Django 4.2.27 on 2026-04-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0008_roledefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('unit', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day')], max_length=16)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RateCardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('bill_rate', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RateCardLineValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('multiply_bill_rate', 'Multiply Bill Rate'), ('add_percent', 'Add Percent'), ('add_amount', 'Add Amount')], default='multiply_bill_rate', max_length=32)),
                ('action_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stop_processing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RateRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('joiner', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=8)),
                ('field_key', models.CharField(max_length=64)),
                ('operator', models.CharField(max_length=16)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RateStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('currency_mode', models.CharField(choices=[('single_currency', 'Single Currency')], default='single_currency', max_length=32)),
                ('rounding_scale', models.PositiveSmallIntegerField(default=2)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RateStructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('currency', 'Currency'), ('percentage', 'Percentage')], max_length=16)),
                ('calculation_role', models.CharField(choices=[('base', 'Base'), ('additive_percent', 'Additive Percent'), ('additive_amount', 'Additive Amount')], max_length=32)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='rates.ratestructure')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ratestructure',
            index=models.Index(fields=['status', 'name'], name='rates_rates_status_bf615b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratestructure',
            constraint=models.CheckConstraint(check=models.Q(('rounding_scale__gte', 0)), name='rates_structure_rounding_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ratestructure',
            constraint=models.CheckConstraint(check=models.Q(('rounding_scale__lte', 6)), name='rates_structure_rounding_lte_6'),
        ),
        migrations.AddField(
            model_name='raterulecondition',
            name='rate_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rates.raterule'),
        ),
        migrations.AddField(
            model_name='raterule',
            name='rate_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_rules', to='rates.ratestructure'),
        ),
        migrations.AddField(
            model_name='raterule',
            name='role_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_rules', to='masterdata.roledefinition'),
        ),
        migrations.AddField(
            model_name='ratecardlinevalue',
            name='rate_card_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_values', to='rates.ratecardline'),
        ),
        migrations.AddField(
            model_name='ratecardlinevalue',
            name='rate_structure_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_values', to='rates.ratestructurecomponent'),
        ),
        migrations.AddField(
            model_name='ratecardline',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rates.ratecard'),
        ),
        migrations.AddField(
            model_name='ratecardline',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_card_lines', to='masterdata.supplier'),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='rate_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_cards', to='rates.ratestructure'),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='role_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_cards', to='masterdata.roledefinition'),
        ),
        migrations.AddIndex(
            model_name='ratestructurecomponent',
            index=models.Index(fields=['rate_structure', 'is_active'], name='rates_rates_rate_st_4cd0e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratestructurecomponent',
            constraint=models.UniqueConstraint(fields=('rate_structure', 'sequence'), name='rates_component_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='ratestructurecomponent',
            constraint=models.UniqueConstraint(fields=('rate_structure', 'code'), name='rates_component_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='ratestructurecomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('calculation_role', 'base')), fields=('rate_structure',), name='rates_component_single_base'),
        ),
        migrations.AddConstraint(
            model_name='ratestructurecomponent',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='rates_component_sequence_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ratestructurecomponent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('calculation_role', 'base'), ('value_type', 'currency')), models.Q(('calculation_role', 'base'), _negated=True), _connector='OR'), name='rates_component_base_requires_currency'),
        ),
        migrations.AddConstraint(
            model_name='ratestructurecomponent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('calculation_role', 'additive_percent'), ('value_type', 'percentage')), models.Q(('calculation_role', 'additive_percent'), _negated=True), _connector='OR'), name='rates_component_percent_requires_percentage'),
        ),
        migrations.AddConstraint(
            model_name='ratestructurecomponent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('calculation_role', 'additive_amount'), ('value_type', 'currency')), models.Q(('calculation_role', 'additive_amount'), _negated=True), _connector='OR'), name='rates_component_amount_requires_currency'),
        ),
        migrations.AddIndex(
            model_name='raterulecondition',
            index=models.Index(fields=['field_key', 'operator'], name='rates_rater_field_k_52586d_idx'),
        ),
        migrations.AddConstraint(
            model_name='raterulecondition',
            constraint=models.UniqueConstraint(fields=('rate_rule', 'sequence'), name='rates_rule_condition_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='raterulecondition',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='rates_rule_condition_sequence_gte_1'),
        ),
        migrations.AddIndex(
            model_name='raterule',
            index=models.Index(fields=['status', 'priority', 'effective_date'], name='rates_rater_status_7f7d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='raterule',
            index=models.Index(fields=['role_definition', 'status', 'effective_date'], name='rates_rater_role_de_4ab3e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='raterule',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 1)), name='rates_rule_priority_gte_1'),
        ),
        migrations.AddIndex(
            model_name='ratecardlinevalue',
            index=models.Index(fields=['rate_card_line', 'rate_structure_component'], name='rates_ratec_rate_ca_bd2722_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratecardlinevalue',
            constraint=models.UniqueConstraint(fields=('rate_card_line', 'rate_structure_component'), name='rates_line_value_unique_component'),
        ),
        migrations.AddIndex(
            model_name='ratecardline',
            index=models.Index(fields=['rate_card', 'supplier'], name='rates_ratec_rate_ca_d2e87c_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratecardline',
            constraint=models.UniqueConstraint(fields=('rate_card', 'sequence'), name='rates_card_line_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='ratecardline',
            constraint=models.UniqueConstraint(fields=('rate_card', 'supplier', 'location_label'), name='rates_card_line_unique_supplier_location'),
        ),
        migrations.AddConstraint(
            model_name='ratecardline',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='rates_card_line_sequence_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ratecardline',
            constraint=models.CheckConstraint(check=models.Q(('bill_rate__gte', 0)), name='rates_card_line_bill_rate_gte_0'),
        ),
        migrations.AddIndex(
            model_name='ratecard',
            index=models.Index(fields=['status', 'effective_date'], name='rates_ratec_status_5b43da_idx'),
        ),
        migrations.AddIndex(
            model_name='ratecard',
            index=models.Index(fields=['role_definition', 'status', 'effective_date'], name='rates_ratec_role_de_386b51_idx'),
        ),
    ]
