# Generated by ChatGPT on 2026-02-22

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[("password", "Password"), ("sso", "SSO")],
                default="password",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("hiring_manager", "Hiring Manager"),
                    ("procurement_manager", "Procurement Manager"),
                    ("finance", "Finance"),
                    ("legal", "Legal"),
                    ("business", "Business"),
                    ("executive", "Executive"),
                    ("supplier", "Supplier User"),
                    ("manager", "Manager"),
                    ("viewer", "Viewer"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("active", "Active"),
                    ("disabled", "Disabled"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="supplier_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                check=Q(role="supplier", supplier_id__isnull=False) | ~Q(role="supplier"),
                name="membership_supplier_requires_supplier_id",
            ),
        ),
    ]
