# Generated by ChatGPT on 2026-02-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_password_policy_models"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSSOConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workos_organization_id", models.CharField(max_length=255)),
                ("workos_connection_id", models.CharField(blank=True, max_length=255, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("default_role", models.CharField(choices=[("admin", "Admin"), ("hiring_manager", "Hiring Manager"), ("procurement_manager", "Procurement Manager"), ("finance", "Finance"), ("legal", "Legal"), ("business", "Business"), ("executive", "Executive"), ("supplier", "Supplier User"), ("manager", "Manager"), ("viewer", "Viewer")], default="business", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="sso_config", to="tenants.tenant")),
            ],
        ),
    ]
