# Generated by Django 4.2.27 on 2026-03-07 04:25

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0004_tenant_sso_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, default=apps.accounts.models._default_supplier_invite_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.accounts.models._default_supplier_invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invites_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invites', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='supplierinvite',
            index=models.Index(fields=['tenant', 'email', 'status'], name='accounts_su_tenant__6e6c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvite',
            index=models.Index(fields=['tenant', 'supplier_id', 'status'], name='accounts_su_tenant__82c3f0_idx'),
        ),
    ]
