# Generated by Django 4.2.27 on 2026-03-08

from django.db import migrations, models


LEGACY_ROLE_MAP = {
    "hiring_manager": "business",
    "procurement_manager": "manager",
    "legal": "viewer",
    "executive": "viewer",
}


def normalize_roles_forward(apps, schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    TenantSSOConfig = apps.get_model("accounts", "TenantSSOConfig")

    for old_role, new_role in LEGACY_ROLE_MAP.items():
        Membership.objects.filter(role=old_role).update(role=new_role)
        TenantSSOConfig.objects.filter(default_role=old_role).update(default_role=new_role)


def normalize_roles_reverse(apps, schema_editor):
    # Legacy roles are intentionally collapsed into simplified roles.
    # Reverse migration keeps the normalized values.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_supplierinvite_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_roles_forward, normalize_roles_reverse),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "System Admin"),
                    ("manager", "Program Manager (PMO)"),
                    ("business", "Business User"),
                    ("supplier", "Supplier User"),
                    ("finance", "Finance User"),
                    ("viewer", "Read Only"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="tenantssoconfig",
            name="default_role",
            field=models.CharField(
                choices=[
                    ("admin", "System Admin"),
                    ("manager", "Program Manager (PMO)"),
                    ("business", "Business User"),
                    ("supplier", "Supplier User"),
                    ("finance", "Finance User"),
                    ("viewer", "Read Only"),
                ],
                default="business",
                max_length=32,
            ),
        ),
    ]
