# Generated by Django 4.2.27 on 2026-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_normalize_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='business_unit_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='cost_center_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
