# Generated by Django 4.2.30 on 2026-08-29 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0007_membership_business_unit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=16)),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(choices=[('work_order', 'Work Order'), ('sow', 'SOW')], default='work_order', max_length=32)),
                ('work_order_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('work_order_number', models.CharField(blank=True, max_length=64)),
                ('sow_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('sow_number', models.CharField(blank=True, max_length=64)),
                ('supplier_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('role_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('ended', 'Ended'), ('disabled', 'Disabled')], db_index=True, default='invited', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_engagements_invited', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_engagements', to='tenants.tenant')),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='accounts.workerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['worker_profile', 'status'], name='accounts_wo_worker__01b15d_idx'), models.Index(fields=['tenant', 'status'], name='accounts_wo_tenant__e42f28_idx'), models.Index(fields=['tenant', 'engagement_type', 'work_order_id'], name='accounts_wo_tenant__0d4020_idx'), models.Index(fields=['tenant', 'engagement_type', 'sow_id'], name='accounts_wo_tenant__dbef70_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workerengagement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('engagement_type', 'work_order'), models.Q(('work_order_id__isnull', False), models.Q(('work_order_number', ''), _negated=True), _connector='OR')), models.Q(('engagement_type', 'sow'), models.Q(('sow_id__isnull', False), models.Q(('sow_number', ''), _negated=True), _connector='OR')), _connector='OR'), name='worker_engagement_requires_reference'),
        ),
    ]
