# Generated by Django 4.2.30 on 2026-07-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_membership_business_unit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('manager', 'Program Manager (PMO)'), ('business', 'Business User'), ('supplier', 'Supplier User'), ('worker', 'Worker'), ('finance', 'Finance User'), ('viewer', 'Read Only')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tenantssoconfig',
            name='default_role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('manager', 'Program Manager (PMO)'), ('business', 'Business User'), ('supplier', 'Supplier User'), ('worker', 'Worker'), ('finance', 'Finance User'), ('viewer', 'Read Only')], default='business', max_length=32),
        ),
    ]
