# Generated by Django 4.2.30 on 2026-10-04 22:24

from django.db import migrations, models


def migrate_disabled_memberships(apps, schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.filter(status="disabled").update(
        status="suspended",
        is_active=False,
    )


def restore_legacy_disabled_memberships(apps, schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.filter(status__in=("suspended", "deactivated")).update(
        status="disabled",
        is_active=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_workerinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="authorization_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.RunPython(
            migrate_disabled_memberships,
            restore_legacy_disabled_memberships,
        ),
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
    ]
