# Generated by Django 4.2.30 on 2026-10-05 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_supplier_contact_access(apps, schema_editor):
    SupplierInvite = apps.get_model('accounts', 'SupplierInvite')
    SupplierContactAccess = apps.get_model('accounts', 'SupplierContactAccess')
    Membership = apps.get_model('accounts', 'Membership')

    access_by_target = {}
    for invitation in SupplierInvite.objects.order_by('created_at', 'id').iterator():
        email = (invitation.email or '').strip().lower()
        key = (invitation.tenant_id, invitation.supplier_id, email)
        access = access_by_target.get(key)
        if access is None:
            membership = Membership.objects.filter(
                tenant_id=invitation.tenant_id,
                role='supplier',
                supplier_id=invitation.supplier_id,
                user__email__iexact=email,
            ).first()
            access = SupplierContactAccess.objects.create(
                tenant_id=invitation.tenant_id,
                supplier_id=invitation.supplier_id,
                email=email,
                membership_id=membership.id if membership else None,
                status='active' if invitation.status == 'accepted' else invitation.status,
                invited_by_id=invitation.invited_by_id,
                accepted_at=invitation.accepted_at,
            )
            access_by_target[key] = access
        elif invitation.status == 'accepted' and access.status != 'active':
            access.status = 'active'
            access.accepted_at = invitation.accepted_at
            access.save(update_fields=['status', 'accepted_at', 'updated_at'])
        invitation.email = email
        invitation.contact_access_id = access.id
        invitation.delivery_status = 'sent'
        invitation.sent_at = invitation.created_at
        invitation.save(update_fields=['email', 'contact_access', 'delivery_status', 'sent_at', 'updated_at'])

    # Preserve legitimate legacy supplier logins that predate invitations by
    # binding every existing supplier membership to an explicit access row.
    for membership in Membership.objects.filter(role='supplier', supplier_id__isnull=False).select_related('user').iterator():
        email = (membership.user.email or membership.user.username or '').strip().lower()
        key = (membership.tenant_id, membership.supplier_id, email)
        access = access_by_target.get(key)
        if access is None:
            access = SupplierContactAccess.objects.filter(
                tenant_id=membership.tenant_id,
                supplier_id=membership.supplier_id,
                email=email,
            ).first()
        access_status = 'active' if membership.status == 'active' and membership.is_active else (
            'pending' if membership.status == 'invited' else 'revoked'
        )
        if access is None:
            access = SupplierContactAccess.objects.create(
                tenant_id=membership.tenant_id,
                supplier_id=membership.supplier_id,
                email=email,
                membership_id=membership.id,
                status=access_status,
            )
            access_by_target[key] = access
        elif access.membership_id is None:
            access.membership_id = membership.id
            access.status = access_status
            access.save(update_fields=['membership', 'status', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0012_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvite',
            name='delivery_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='token_hint',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='supplierinvite',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SupplierContactAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_contact_access_invited', to=settings.AUTH_USER_MODEL)),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_contact_access', to='accounts.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contact_access', to='tenants.tenant')),
            ],
            options={
                'ordering': ['email', 'id'],
            },
        ),
        migrations.AddField(
            model_name='supplierinvite',
            name='contact_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.suppliercontactaccess'),
        ),
        migrations.RunPython(backfill_supplier_contact_access, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='suppliercontactaccess',
            index=models.Index(fields=['tenant', 'supplier_id', 'status'], name='acc_scontact_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercontactaccess',
            constraint=models.UniqueConstraint(fields=('tenant', 'supplier_id', 'email'), name='supplier_contact_access_unique_target'),
        ),
    ]
