# Generated by Django 4.2.27 on 2026-03-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(max_length=64)),
                ('region_in_country', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'country', 'region_in_country'],
                'indexes': [models.Index(fields=['role'], name='masterdata__role_4d4041_idx'), models.Index(fields=['country', 'region_in_country'], name='masterdata__country_89ff6b_idx')],
                'unique_together': {('role', 'country', 'region_in_country')},
            },
        ),
    ]
