# Generated by Django 4.2.27 on 2026-03-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_jobtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='active_sows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='active_workers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='compliance_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('review_required', 'Review Required'), ('non_compliant', 'Non-Compliant')], default='compliant', max_length=32),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='diversity_status',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='supplier',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('staffing', 'Staffing'), ('services', 'Services'), ('both', 'Both')], default='staffing', max_length=16),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
