# Generated by Django 4.2.27 on 2026-03-08

from django.db import migrations


FORWARD_SQL = """
CREATE OR REPLACE FUNCTION masterdata_set_supplier_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.id IS NULL THEN
        NEW.id := nextval(pg_get_serial_sequence('masterdata_supplier', 'id'));
    END IF;

    IF NEW.supplier_code IS NULL OR btrim(NEW.supplier_code) = '' THEN
        NEW.supplier_code := 'SUP-' || lpad(NEW.id::text, 5, '0');
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_masterdata_supplier_code ON masterdata_supplier;
CREATE TRIGGER trg_masterdata_supplier_code
BEFORE INSERT OR UPDATE ON masterdata_supplier
FOR EACH ROW
EXECUTE FUNCTION masterdata_set_supplier_code();

UPDATE masterdata_supplier
SET supplier_code = 'SUP-' || lpad(id::text, 5, '0')
WHERE supplier_code IS NULL OR btrim(supplier_code) = '';
"""


REVERSE_SQL = """
DROP TRIGGER IF EXISTS trg_masterdata_supplier_code ON masterdata_supplier;
DROP FUNCTION IF EXISTS masterdata_set_supplier_code();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("masterdata", "0004_alter_supplier_status"),
    ]

    operations = [
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
