# Generated by Django 4.2.27 on 2026-04-01 18:00

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def populate_business_unit_codes(apps, schema_editor):
    BusinessUnit = apps.get_model("masterdata", "BusinessUnit")
    for business_unit in BusinessUnit.objects.filter(Q(code__isnull=True) | Q(code="")).iterator():
        business_unit.code = str(business_unit.id)
        business_unit.save(update_fields=["code"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0005_supplier_code_autogen"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessunit",
            name="code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(populate_business_unit_codes, noop_reverse),
        migrations.AlterField(
            model_name="businessunit",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="businessunit",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessunit",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="gl_account_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="legal_entity_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="masterdata.businessunit",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("closed", "Closed")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="businessunit",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_units",
                to="masterdata.company",
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                db_column="business_unit_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_centers",
                to="masterdata.businessunit",
                to_field="code",
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="budget_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="budget_period",
            field=models.CharField(
                blank=True,
                choices=[("annual", "Annual"), ("quarterly", "Quarterly"), ("project", "Project")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="costcenter",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="erp_code",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="gl_account_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="legal_entity_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="owner_email",
            field=models.EmailField(default="unassigned@example.com", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="costcenter",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("closed", "Closed")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.CheckConstraint(
                check=Q(budget_amount__isnull=True) | Q(budget_amount__gte=0),
                name="costcenter_budget_non_negative",
            ),
        ),
    ]
