# Generated by Django 4.2.27 on 2026-04-01

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def populate_site_code_and_address(apps, schema_editor):
    Site = apps.get_model("masterdata", "Site")
    for site in Site.objects.all().iterator():
        updates = {}
        if not site.code:
            updates["code"] = str(site.id)
        if not site.address_line1 and getattr(site, "address", ""):
            updates["address_line1"] = site.address
        if updates:
            Site.objects.filter(pk=site.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("masterdata", "0006_businessunit_costcenter_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                ("id", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=2)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(max_length=3)),
                ("erp_code", models.CharField(blank=True, max_length=200)),
                ("billing_address", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="site",
            name="code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="site",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("closed", "Closed")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="address_line1",
            field=models.CharField(default="", max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="address_line2",
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="site",
            name="city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="state_province",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="country",
            field=models.CharField(default="US", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="postal_code",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="hours_per_day",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="hours_per_week",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="site",
            name="legal_entity",
            field=models.ForeignKey(
                blank=True,
                db_column="legal_entity_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="masterdata.legalentity",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="tax_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="site",
            name="erp_code",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="site",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(populate_site_code_and_address, noop_reverse),
        migrations.AlterField(
            model_name="site",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name="site",
            name="address",
        ),
    ]
