# Generated by Django 4.2.27 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0007_legalentity_site_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("country", models.CharField(max_length=2)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                (
                    "default_unit",
                    models.CharField(
                        choices=[("hour", "Hour"), ("day", "Day")],
                        default="hour",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "country", "region", "city", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="roledefinition",
            constraint=models.UniqueConstraint(
                fields=("name", "country", "region", "city"),
                name="roledefinition_unique_market",
            ),
        ),
        migrations.AddIndex(
            model_name="roledefinition",
            index=models.Index(fields=["name"], name="masterdata__name_1720d6_idx"),
        ),
        migrations.AddIndex(
            model_name="roledefinition",
            index=models.Index(fields=["country", "region", "city"], name="masterdata__country_552324_idx"),
        ),
    ]
