# Generated by Django 4.2.27 on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterdata", "0008_roledefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=64)),
                ("region", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "country", "region", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("name", "country", "region"),
                name="location_unique_name_country_region",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["name"], name="masterdata__name_b39fbf_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["country", "region"], name="masterdata__country_28c6b8_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["status"], name="masterdata__status_db7d46_idx"),
        ),
    ]
