# Generated by Django 4.2.30 on 2026-10-05 15:18

from django.db import migrations, models


def backfill_supplier_detail_fields(apps, schema_editor):
    Supplier = apps.get_model("masterdata", "Supplier")
    Supplier.objects.filter(status="inactive").update(active_in_levv=False)
    Supplier.objects.filter(service_type="").update(service_type=models.F("supplier_type"))


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='active_in_levv',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_units',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplier',
            name='buying_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplier',
            name='hq_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registered_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supplier',
            name='service_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='source_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='source_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='source_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='source_system',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_supplier_detail_fields, migrations.RunPython.noop),
    ]
