# Generated by Django 4.2.30 on 2026-10-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_supplier_active_in_levv_supplier_business_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_coverage_records', to='masterdata.roledefinition')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_coverage_records', to='masterdata.site')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='masterdata.supplier')),
            ],
            options={
                'ordering': ['role__name', 'site__name', 'id'],
                'indexes': [models.Index(fields=['supplier', 'is_active'], name='supp_cov_supplier_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='suppliercoverage',
            constraint=models.UniqueConstraint(fields=('supplier', 'role', 'site'), name='supplier_coverage_unique_role_site'),
        ),
    ]
