# Generated by Django 4.2.27 on 2026-04-08

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalChain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=50)),
                (
                    "match_strategy",
                    models.CharField(
                        choices=[("all", "All Conditions"), ("any", "Any Condition")],
                        default="all",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalChainCondition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("field_key", models.CharField(max_length=128)),
                ("operator", models.CharField(max_length=32)),
                ("value_json", models.JSONField(blank=True, null=True)),
                (
                    "approval_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="approvals.approvalchain",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
                "unique_together": {("approval_chain", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalChainStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "step_type",
                    models.CharField(
                        choices=[("specific_user", "Specific User")],
                        default="specific_user",
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "approval_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="approvals.approvalchain",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_chain_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
                "unique_together": {("approval_chain", "sequence")},
            },
        ),
        migrations.AddIndex(
            model_name="approvalchain",
            index=models.Index(fields=["is_active", "priority"], name="approvals_a_is_acti_af4199_idx"),
        ),
        migrations.AddConstraint(
            model_name="approvalchain",
            constraint=models.CheckConstraint(check=Q(("priority__gte", 1)), name="approval_chain_priority_gte_1"),
        ),
        migrations.AddIndex(
            model_name="approvalchaincondition",
            index=models.Index(fields=["approval_chain", "sequence"], name="approvals_a_approva_bd06e1_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalchaincondition",
            index=models.Index(fields=["field_key", "operator"], name="approvals_a_field_k_f4a5ac_idx"),
        ),
        migrations.AddConstraint(
            model_name="approvalchaincondition",
            constraint=models.CheckConstraint(check=Q(("sequence__gte", 1)), name="approval_condition_sequence_gte_1"),
        ),
        migrations.AddIndex(
            model_name="approvalchainstep",
            index=models.Index(fields=["approval_chain", "sequence"], name="approvals_a_approva_e02794_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalchainstep",
            index=models.Index(fields=["approver"], name="approvals_a_approve_c3882c_idx"),
        ),
        migrations.AddConstraint(
            model_name="approvalchainstep",
            constraint=models.CheckConstraint(check=Q(("sequence__gte", 1)), name="approval_step_sequence_gte_1"),
        ),
        migrations.AddConstraint(
            model_name="approvalchainstep",
            constraint=models.CheckConstraint(check=Q(("amount__gte", 0)), name="approval_step_amount_gte_0"),
        ),
    ]
