# Generated by Django 4.2.30 on 2026-07-26 04:25

import apps.workers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0005_alter_fieldpolicy_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('engagement_number', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending_supplier_acceptance', 'Pending Supplier Acceptance'), ('accepted', 'Accepted'), ('changes_requested', 'Changes Requested'), ('cancelled', 'Cancelled')], db_index=True, default='pending_supplier_acceptance', max_length=40)),
                ('supplier_response_notes', models.TextField(blank=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('change_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_accepted', to=settings.AUTH_USER_MODEL)),
                ('change_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_changes_requested', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_created', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='engagement', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('offboarding', 'Offboarding'), ('offboarded', 'Offboarded')], db_index=True, default='invited', max_length=24)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkerEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('worker_type', models.CharField(choices=[('contingent', 'Contingent'), ('employee', 'Employee'), ('contractor', 'Contractor')], db_index=True, default='contingent', max_length=32)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('offboarding', 'Offboarding'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], db_index=True, default='onboarding', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='worker_engagement', to='workers.engagement')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('lifecycle_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], db_index=True, max_length=24)),
                ('workflow_name', models.CharField(max_length=255)),
                ('workflow_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_runs', to='workers.workerengagement')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_runs', to='policies.workerlifecycleworkflow')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_block_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('client_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('block_type', models.CharField(choices=[('requirement', 'Requirement'), ('system', 'System')], max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('gate_type', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default='hard', max_length=16)),
                ('integration_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('gated', 'Gated'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('complete', 'Complete'), ('skipped', 'Skipped')], db_index=True, default='gated', max_length=24)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workers.lifecyclerun')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_requirement_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(choices=[('worker', 'Worker'), ('supplier', 'Supplier'), ('hiring_manager', 'Hiring Manager'), ('it', 'IT'), ('system', 'System')], db_index=True, default='worker', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('complete', 'Complete'), ('waived', 'Waived')], db_index=True, default='pending', max_length=24)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workers.lifecycleblock')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_activities_completed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, default=apps.workers.models._default_worker_invite_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.workers.models._default_worker_invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_invites_accepted', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_invites', to='workers.engagement')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['worker', 'email', 'status'], name='workers_wor_worker__76ab47_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workerengagement',
            index=models.Index(fields=['tenant_id', 'status'], name='workers_wor_tenant__bea59e_idx'),
        ),
        migrations.AddIndex(
            model_name='workerengagement',
            index=models.Index(fields=['worker', 'status'], name='workers_wor_worker__63debf_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['tenant_id', 'status'], name='workers_wor_tenant__247743_idx'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='worker_email_case_insensitive_unique'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='worker_user_unique_when_set'),
        ),
        migrations.AddIndex(
            model_name='lifecyclerun',
            index=models.Index(fields=['tenant_id', 'lifecycle_type', 'status'], name='workers_lif_tenant__cc7097_idx'),
        ),
        migrations.AddConstraint(
            model_name='lifecyclerun',
            constraint=models.UniqueConstraint(fields=('worker_engagement', 'lifecycle_type'), name='worker_engagement_lifecycle_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleblock',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='lifecycle_block_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleblock',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key__gt', '')), fields=('run', 'client_key'), name='lifecycle_block_unique_client_key'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleactivity',
            constraint=models.UniqueConstraint(fields=('block', 'sequence'), name='lifecycle_activity_unique_sequence'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['tenant_id', 'status', 'created_at'], name='workers_eng_tenant__977e7c_idx'),
        ),
    ]
