# Generated by Django 4.2.30 on 2026-07-29 23:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


def backfill_work_order_assignments(apps, schema_editor):
    Engagement = apps.get_model("workers", "Engagement")
    WorkerEngagement = apps.get_model("workers", "WorkerEngagement")
    WorkerInvite = apps.get_model("workers", "WorkerInvite")
    WorkOrder = apps.get_model("workorders", "WorkOrder")

    status_map = {
        "pending_supplier_acceptance": "pending",
        "accepted": "accepted",
        "changes_requested": "changes_requested",
    }
    for engagement in Engagement.objects.all().iterator():
        WorkOrder.objects.filter(pk=engagement.work_order_id).update(
            supplier_acceptance_status=status_map.get(
                engagement.status,
                "not_started",
            ),
            supplier_response_notes=engagement.supplier_response_notes,
            supplier_accepted_at=engagement.accepted_at,
            supplier_accepted_by_id=engagement.accepted_by_id,
            supplier_change_requested_at=engagement.change_requested_at,
            supplier_change_requested_by_id=engagement.change_requested_by_id,
        )
        WorkerEngagement.objects.filter(
            engagement_id=engagement.id,
            work_order_id__isnull=True,
        ).update(work_order_id=engagement.work_order_id)
        WorkerInvite.objects.filter(
            engagement_id=engagement.id,
            work_order_id__isnull=True,
        ).update(work_order_id=engagement.work_order_id)


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorder_supplier_acceptance_status_and_more'),
        ('workers', '0002_backfill_approved_engagements'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worker',
            name='worker_email_case_insensitive_unique',
        ),
        migrations.AddField(
            model_name='workerengagement',
            name='work_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_assignment', to='workorders.workorder'),
        ),
        migrations.AddField(
            model_name='workerinvite',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_invites', to='workorders.workorder'),
        ),
        migrations.AlterField(
            model_name='workerengagement',
            name='engagement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_engagement', to='workers.engagement'),
        ),
        migrations.RunPython(
            backfill_work_order_assignments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('tenant_id'), name='worker_tenant_email_case_insensitive_unique'),
        ),
    ]
