# Generated by ChatGPT on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(max_length=64)),
                ("field_name", models.CharField(max_length=128)),
                ("role", models.CharField(choices=[
                    ("admin", "Admin"),
                    ("hiring_manager", "Hiring Manager"),
                    ("procurement_manager", "Procurement Manager"),
                    ("finance", "Finance"),
                    ("legal", "Legal"),
                    ("business", "Business"),
                    ("executive", "Executive"),
                    ("supplier", "Supplier User"),
                    ("manager", "Manager"),
                    ("viewer", "Viewer"),
                ], max_length=32)),
                ("can_read", models.BooleanField(default=True)),
                ("can_write", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("role", "model", "field_name")},
            },
        ),
        migrations.AddIndex(
            model_name="fieldpolicy",
            index=models.Index(fields=["model", "role"], name="fieldpolicy_model_role_idx"),
        ),
    ]
