# Generated by Django 4.2.27 on 2026-04-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fieldpolicy',
            new_name='policies_fi_model_ae5b1d_idx',
            old_name='fieldpolicy_model_role_idx',
        ),
        migrations.AlterField(
            model_name='fieldpolicy',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('manager', 'Program Manager (PMO)'), ('business', 'Business User'), ('supplier', 'Supplier User'), ('finance', 'Finance User'), ('viewer', 'Read Only')], max_length=32),
        ),
    ]
