# Generated by Django 4.2.27 on 2026-06-15 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0009_location'),
        ('policies', '0002_rename_fieldpolicy_model_role_idx_policies_fi_model_ae5b1d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerLifecycleWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('workflow_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], db_index=True, default='onboarding', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_lifecycle_workflows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workflow_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('block_type', models.CharField(choices=[('requirement', 'Requirement'), ('system', 'System')], max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('gate_type', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default='hard', max_length=16)),
                ('integration_type', models.CharField(blank=True, choices=[('api_call', 'API Call')], max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='policies.workerlifecycleworkflow')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPolicyScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(blank=True, choices=[('contingent', 'Contingent'), ('employee', 'Employee'), ('contractor', 'Contractor')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_scope', to='policies.workerlifecycleworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(blank=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_owner', models.CharField(choices=[('worker', 'Worker'), ('supplier', 'Supplier'), ('hiring_manager', 'Hiring Manager'), ('it', 'IT'), ('system', 'System')], default='worker', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='policies_wo_tenant__6423d0_idx'), models.Index(fields=['name'], name='policies_wo_name_574655_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBlockRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(choices=[('worker', 'Worker'), ('supplier', 'Supplier'), ('hiring_manager', 'Hiring Manager'), ('it', 'IT'), ('system', 'System')], default='worker', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='policies.workflowblock')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='block_instances', to='policies.workflowrequirement')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPolicyScopeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('field_key', models.CharField(choices=[('location', 'Location'), ('cost_center', 'Cost Center'), ('business_unit', 'Business Unit'), ('role', 'Role'), ('supplier', 'Supplier')], max_length=32)),
                ('operator', models.CharField(choices=[('equals', 'Equals')], default='equals', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_scope_fields', to='masterdata.businessunit')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_scope_fields', to='masterdata.costcenter')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_scope_fields', to='masterdata.location')),
                ('role_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_scope_fields', to='masterdata.roledefinition')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='policies.workflowpolicyscope')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_scope_fields', to='masterdata.supplier')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['field_key'], name='policies_wo_field_k_e5a97d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowpolicyscopefield',
            constraint=models.UniqueConstraint(fields=('scope', 'sequence'), name='workflow_scope_field_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='workflowpolicyscopefield',
            constraint=models.UniqueConstraint(fields=('scope', 'field_key'), name='workflow_scope_field_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='workflowpolicyscopefield',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='workflow_scope_field_sequence_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='workflowblockrequirement',
            constraint=models.UniqueConstraint(fields=('block', 'sequence'), name='workflow_block_req_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='workflowblockrequirement',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='workflow_block_req_sequence_gte_1'),
        ),
        migrations.AddIndex(
            model_name='workflowblock',
            index=models.Index(fields=['workflow', 'block_type'], name='policies_wo_workflo_53a06e_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowblock',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='workflow_block_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='workflowblock',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='workflow_block_sequence_gte_1'),
        ),
        migrations.AddIndex(
            model_name='workerlifecycleworkflow',
            index=models.Index(fields=['tenant_id', 'workflow_type', 'status'], name='policies_wo_tenant__80de82_idx'),
        ),
        migrations.AddIndex(
            model_name='workerlifecycleworkflow',
            index=models.Index(fields=['tenant_id', 'is_active', 'workflow_type'], name='policies_wo_tenant__49e15d_idx'),
        ),
        migrations.AddConstraint(
            model_name='workerlifecycleworkflow',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='worker_workflow_version_gte_1'),
        ),
    ]
