# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_workerlifecycleworkflow_workflowblock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerlifecycleworkflow",
            name="dependencies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workflowblock",
            name="client_key",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="workflowblock",
            name="layout",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name="workflowblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_key__gt", "")),
                fields=("workflow", "client_key"),
                name="workflow_block_unique_client_key",
            ),
        ),
    ]
