# Generated by Django 4.2.30 on 2026-07-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_workflow_graph_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpolicy',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('manager', 'Program Manager (PMO)'), ('business', 'Business User'), ('supplier', 'Supplier User'), ('worker', 'Worker'), ('finance', 'Finance User'), ('viewer', 'Read Only')], max_length=32),
        ),
    ]
