# Generated by Codex on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0004_workflow_graph_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowpolicyscope",
            name="worker_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contingent", "Contingent"),
                    ("employee", "Employee"),
                    ("contractor", "Contractor"),
                    ("sow", "SOW"),
                    ("non_transactional", "Non-transactional"),
                    ("independent_contractor", "Independent contractor"),
                    ("temp_agency", "Temp / Agency"),
                    ("consultant", "Consultant"),
                    ("intern", "Intern"),
                    ("freelancer", "Freelancer"),
                ],
                max_length=32,
            ),
        ),
    ]
