# Generated by Django 4.2.30 on 2026-08-30 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_add_worker_profiles_and_engagements'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(max_length=32)),
                ('work_order_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('work_order_number', models.CharField(blank=True, max_length=64)),
                ('sow_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('sow_number', models.CharField(blank=True, max_length=64)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('voided', 'Voided')], db_index=True, default='draft', max_length=16)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('qa_issues', models.JSONField(blank=True, default=list)),
                ('jurisdiction_flags', models.JSONField(blank=True, default=list)),
                ('approval_brief', models.JSONField(blank=True, default=dict)),
                ('assignment_snapshot', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets_approved', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets_submitted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='tenants.tenant')),
                ('worker_engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='accounts.workerengagement')),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('voided', 'Voided')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_events', to=settings.AUTH_USER_MODEL)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timesheets.timesheet')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField()),
                ('task_name', models.CharField(max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost_center_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cost_center_code', models.CharField(blank=True, max_length=200)),
                ('cost_center_name', models.CharField(blank=True, max_length=200)),
                ('task_code', models.CharField(blank=True, max_length=100)),
                ('allocation_rationale', models.CharField(blank=True, max_length=500)),
                ('rate_category', models.CharField(blank=True, max_length=64)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='timesheets.timesheet')),
            ],
            options={
                'ordering': ['line_date', 'id'],
                'indexes': [models.Index(fields=['timesheet', 'line_date'], name='timesheets__timeshe_ca8729_idx'), models.Index(fields=['cost_center_id'], name='timesheets__cost_ce_bffb36_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='timesheetline',
            constraint=models.CheckConstraint(check=models.Q(('hours__gte', 0)), name='timesheetline_hours_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='timesheetline',
            constraint=models.CheckConstraint(check=models.Q(('bill_amount__isnull', True), ('bill_amount__gte', 0), _connector='OR'), name='timesheetline_bill_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='timesheetline',
            constraint=models.CheckConstraint(check=models.Q(('pay_amount__isnull', True), ('pay_amount__gte', 0), _connector='OR'), name='timesheetline_pay_amount_gte_0'),
        ),
        migrations.AddIndex(
            model_name='timesheetevent',
            index=models.Index(fields=['timesheet', 'created_at'], name='timesheets__timeshe_1e8672_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetevent',
            index=models.Index(fields=['action', 'created_at'], name='timesheets__action_1e9c50_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'status', 'period_start'], name='timesheets__tenant__00ca7c_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['worker_profile', 'status'], name='timesheets__worker__9d6584_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['worker_engagement', 'period_start'], name='timesheets__worker__6eb14c_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'work_order_id', 'period_start'], name='timesheets__tenant__a757c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('total_hours__gte', 0)), name='timesheet_total_hours_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('regular_hours__gte', 0)), name='timesheet_regular_hours_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('overtime_hours__gte', 0)), name='timesheet_overtime_hours_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='timesheet_period_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'voided'), _negated=True), fields=('worker_engagement', 'period_start', 'period_end'), name='timesheet_unique_active_engagement_period'),
        ),
    ]
